export const GET_SAMPLE = 'GET_SAMPLE';
export const SAMPLE_ERROR = 'SAMPLE_ERROR';

export const GET_SAMPLE_DETAILS = 'GET_SAMPLE_DETAILS';
export const SAMPLE_DETAILS_ERROR = 'SAMPLE_DETAILS_ERROR';
